// Mocks generated by Mockito 5.4.6 from annotations
// in ajenda_app/test/features/profile/profile_cubit_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:ajenda_app/core/storage/secure_storage_service.dart' as _i10;
import 'package:ajenda_app/features/profile/data/models/change_email_request.dart'
    as _i8;
import 'package:ajenda_app/features/profile/data/models/change_password_request.dart'
    as _i7;
import 'package:ajenda_app/features/profile/data/models/confirm_change_email_request.dart'
    as _i9;
import 'package:ajenda_app/features/profile/data/models/profile_model.dart'
    as _i5;
import 'package:ajenda_app/features/profile/data/models/update_profile_request.dart'
    as _i6;
import 'package:ajenda_app/features/profile/domain/repositories/profile_repository.dart'
    as _i3;
import 'package:dartz/dartz.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [ProfileRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockProfileRepository extends _i1.Mock implements _i3.ProfileRepository {
  MockProfileRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<String, _i5.ProfileModel>> getProfile() =>
      (super.noSuchMethod(
            Invocation.method(#getProfile, []),
            returnValue: _i4.Future<_i2.Either<String, _i5.ProfileModel>>.value(
              _FakeEither_0<String, _i5.ProfileModel>(
                this,
                Invocation.method(#getProfile, []),
              ),
            ),
          )
          as _i4.Future<_i2.Either<String, _i5.ProfileModel>>);

  @override
  _i4.Future<_i2.Either<String, _i5.ProfileModel>> updateProfile(
    _i6.UpdateProfileRequest? request,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateProfile, [request]),
            returnValue: _i4.Future<_i2.Either<String, _i5.ProfileModel>>.value(
              _FakeEither_0<String, _i5.ProfileModel>(
                this,
                Invocation.method(#updateProfile, [request]),
              ),
            ),
          )
          as _i4.Future<_i2.Either<String, _i5.ProfileModel>>);

  @override
  _i4.Future<_i2.Either<String, void>> changePassword(
    _i7.ChangePasswordRequest? request,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#changePassword, [request]),
            returnValue: _i4.Future<_i2.Either<String, void>>.value(
              _FakeEither_0<String, void>(
                this,
                Invocation.method(#changePassword, [request]),
              ),
            ),
          )
          as _i4.Future<_i2.Either<String, void>>);

  @override
  _i4.Future<_i2.Either<String, void>> changeEmail(
    _i8.ChangeEmailRequest? request,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#changeEmail, [request]),
            returnValue: _i4.Future<_i2.Either<String, void>>.value(
              _FakeEither_0<String, void>(
                this,
                Invocation.method(#changeEmail, [request]),
              ),
            ),
          )
          as _i4.Future<_i2.Either<String, void>>);

  @override
  _i4.Future<_i2.Either<String, void>> confirmChangeEmail(
    _i9.ConfirmChangeEmailRequest? request,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#confirmChangeEmail, [request]),
            returnValue: _i4.Future<_i2.Either<String, void>>.value(
              _FakeEither_0<String, void>(
                this,
                Invocation.method(#confirmChangeEmail, [request]),
              ),
            ),
          )
          as _i4.Future<_i2.Either<String, void>>);

  @override
  _i4.Future<_i2.Either<String, String>> uploadAvatar(String? filePath) =>
      (super.noSuchMethod(
            Invocation.method(#uploadAvatar, [filePath]),
            returnValue: _i4.Future<_i2.Either<String, String>>.value(
              _FakeEither_0<String, String>(
                this,
                Invocation.method(#uploadAvatar, [filePath]),
              ),
            ),
          )
          as _i4.Future<_i2.Either<String, String>>);

  @override
  _i4.Future<_i2.Either<String, void>> deleteAvatar() =>
      (super.noSuchMethod(
            Invocation.method(#deleteAvatar, []),
            returnValue: _i4.Future<_i2.Either<String, void>>.value(
              _FakeEither_0<String, void>(
                this,
                Invocation.method(#deleteAvatar, []),
              ),
            ),
          )
          as _i4.Future<_i2.Either<String, void>>);
}

/// A class which mocks [SecureStorageService].
///
/// See the documentation for Mockito's code generation for more information.
class MockSecureStorageService extends _i1.Mock
    implements _i10.SecureStorageService {
  MockSecureStorageService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<void> saveAccessToken(String? token) =>
      (super.noSuchMethod(
            Invocation.method(#saveAccessToken, [token]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<String?> getAccessToken() =>
      (super.noSuchMethod(
            Invocation.method(#getAccessToken, []),
            returnValue: _i4.Future<String?>.value(),
          )
          as _i4.Future<String?>);

  @override
  _i4.Future<void> deleteAccessToken() =>
      (super.noSuchMethod(
            Invocation.method(#deleteAccessToken, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> saveRefreshToken(String? token) =>
      (super.noSuchMethod(
            Invocation.method(#saveRefreshToken, [token]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<String?> getRefreshToken() =>
      (super.noSuchMethod(
            Invocation.method(#getRefreshToken, []),
            returnValue: _i4.Future<String?>.value(),
          )
          as _i4.Future<String?>);

  @override
  _i4.Future<void> deleteRefreshToken() =>
      (super.noSuchMethod(
            Invocation.method(#deleteRefreshToken, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> saveUserId(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#saveUserId, [userId]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<String?> getUserId() =>
      (super.noSuchMethod(
            Invocation.method(#getUserId, []),
            returnValue: _i4.Future<String?>.value(),
          )
          as _i4.Future<String?>);

  @override
  _i4.Future<void> deleteUserId() =>
      (super.noSuchMethod(
            Invocation.method(#deleteUserId, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> saveEmail(String? email) =>
      (super.noSuchMethod(
            Invocation.method(#saveEmail, [email]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<String?> getEmail() =>
      (super.noSuchMethod(
            Invocation.method(#getEmail, []),
            returnValue: _i4.Future<String?>.value(),
          )
          as _i4.Future<String?>);

  @override
  _i4.Future<void> deleteEmail() =>
      (super.noSuchMethod(
            Invocation.method(#deleteEmail, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> saveFirstName(String? name) =>
      (super.noSuchMethod(
            Invocation.method(#saveFirstName, [name]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<String?> getFirstName() =>
      (super.noSuchMethod(
            Invocation.method(#getFirstName, []),
            returnValue: _i4.Future<String?>.value(),
          )
          as _i4.Future<String?>);

  @override
  _i4.Future<void> saveLastName(String? name) =>
      (super.noSuchMethod(
            Invocation.method(#saveLastName, [name]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<String?> getLastName() =>
      (super.noSuchMethod(
            Invocation.method(#getLastName, []),
            returnValue: _i4.Future<String?>.value(),
          )
          as _i4.Future<String?>);

  @override
  _i4.Future<void> saveAvatar(String? url) =>
      (super.noSuchMethod(
            Invocation.method(#saveAvatar, [url]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<String?> getAvatar() =>
      (super.noSuchMethod(
            Invocation.method(#getAvatar, []),
            returnValue: _i4.Future<String?>.value(),
          )
          as _i4.Future<String?>);

  @override
  _i4.Future<void> deleteAvatar() =>
      (super.noSuchMethod(
            Invocation.method(#deleteAvatar, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> saveUserData({
    required String? userId,
    required String? email,
    String? firstName,
    String? lastName,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#saveUserData, [], {
              #userId: userId,
              #email: email,
              #firstName: firstName,
              #lastName: lastName,
            }),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> clearAll() =>
      (super.noSuchMethod(
            Invocation.method(#clearAll, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);
}
